/** Шаблоны статей блога: нишевые + общие. Цель — 700+ уникальных материалов. */

const NICHE_ARTICLE_TEMPLATES = [
  {
    slug: (n) => `kak-vybrat-crm-dlya-${n.slugBase}`,
    category: 'crm',
    title: (n) => `Как выбрать CRM для ${n.genitive} в 2026 году`,
    h1: (n) => `Как выбрать CRM для ${n.genitive}`,
    articleType: 'guide',
  },
  {
    slug: (n) => `kak-nastroit-online-zapis-dlya-${n.slugBase}`,
    category: 'online-booking',
    title: (n) => `Как настроить онлайн-запись для ${n.genitive}: пошагово`,
    h1: (n) => `Как настроить онлайн-запись для ${n.genitive}`,
    articleType: 'howto',
  },
  {
    slug: (n) => `upravlenie-klientami-v-${n.slugBase}`,
    category: 'client-management',
    title: (n) => `Управление клиентами в ${n.genitive}: практическое руководство`,
    h1: (n) => `Управление клиентами в ${n.genitive}`,
    articleType: 'guide',
  },
  {
    slug: (n) => `pochemu-${n.slugBase}-nuzhna-crm`,
    category: 'crm',
    title: (n) => `Почему ${n.genitive} нужна CRM в 2026 году`,
    h1: (n) => `Почему ${n.genitive} нужна CRM`,
    articleType: 'opinion',
  },
  {
    slug: (n) => `onlajn-zapis-dlya-${n.slugBase}-rukovodstvo`,
    category: 'online-booking',
    title: (n) => `Онлайн-запись для ${n.genitive}: полное руководство`,
    h1: (n) => `Онлайн-запись для ${n.genitive}: руководство`,
    articleType: 'guide',
  },
  {
    slug: (n) => `kak-vesti-bazu-klientov-${n.slugBase}`,
    category: 'client-management',
    title: (n) => `Как вести базу клиентов ${n.genitive}`,
    h1: (n) => `Как вести базу клиентов ${n.genitive}`,
    articleType: 'howto',
  },
  {
    slug: (n) => `crm-dlya-${n.slugBase}-obzor`,
    category: 'crm',
    title: (n) => `CRM для ${n.genitive}: обзор и выбор сервиса`,
    h1: (n) => `CRM для ${n.genitive}`,
    articleType: 'guide',
  },
  {
    slug: (n) => `onlajn-zapis-cherez-telegram-dlya-${n.slugBase}`,
    category: 'online-booking',
    title: (n) => `Онлайн-запись клиентов через Telegram для ${n.genitive}`,
    h1: (n) => `Онлайн-запись через Telegram для ${n.genitive}`,
    articleType: 'howto',
  },
  {
    slug: (n) => `onlajn-zapis-cherez-max-dlya-${n.slugBase}`,
    category: 'online-booking',
    title: (n) => `Онлайн-запись через MAX для ${n.genitive}`,
    h1: (n) => `Онлайн-запись через MAX для ${n.genitive}`,
    articleType: 'howto',
  },
  {
    slug: (n) => `chem-zamenit-dikidi-dlya-${n.slugBase}`,
    category: 'compare',
    title: (n) => `Чем заменить DIKIDI для ${n.genitive}`,
    h1: (n) => `Чем заменить DIKIDI для ${n.genitive}`,
    articleType: 'compare',
    competitor: 'DIKIDI',
  },
  {
    slug: (n) => `chem-zamenit-yclients-dlya-${n.slugBase}`,
    category: 'compare',
    title: (n) => `Чем заменить YCLIENTS для ${n.genitive}`,
    h1: (n) => `Чем заменить YCLIENTS для ${n.genitive}`,
    articleType: 'compare',
    competitor: 'YCLIENTS',
  },
  {
    slug: (n) => `chem-zamenit-altegio-dlya-${n.slugBase}`,
    category: 'compare',
    title: (n) => `Чем заменить Altegio для ${n.genitive}`,
    h1: (n) => `Чем заменить Altegio для ${n.genitive}`,
    articleType: 'compare',
    competitor: 'Altegio',
  },
  {
    slug: (n) => `luchshie-crm-dlya-${n.slugBase}`,
    category: 'crm',
    title: (n) => `Лучшие CRM для ${n.genitive} в 2026 году`,
    h1: (n) => `Лучшие CRM для ${n.genitive}`,
    articleType: 'guide',
  },
  {
    slug: (n) => `avtomatizaciya-zapisi-dlya-${n.slugBase}`,
    category: 'automation',
    title: (n) => `Автоматизация записи клиентов для ${n.genitive}`,
    h1: (n) => `Автоматизация записи для ${n.genitive}`,
    articleType: 'guide',
  },
  {
    slug: (n) => `napominaniya-klientam-dlya-${n.slugBase}`,
    category: 'automation',
    title: (n) => `Напоминания клиентам для ${n.genitive}: как снизить неявки`,
    h1: (n) => `Напоминания клиентам в ${n.genitive}`,
    articleType: 'howto',
  },
  {
    slug: (n) => `baza-klientov-dlya-${n.slugBase}-sovety`,
    category: 'client-management',
    title: (n) => `База клиентов для ${n.genitive}: 10 практических советов`,
    h1: (n) => `База клиентов для ${n.genitive}`,
    articleType: 'guide',
  },
];

const COMPARE_ARTICLE_COMPETITORS = [
  { competitor: 'yclients', label: 'YCLIENTS' },
  { competitor: 'dikidi', label: 'DIKIDI' },
  { competitor: 'altegio', label: 'Altegio' },
  { competitor: 'easyweek', label: 'EasyWeek' },
];

/** Общие статьи (без привязки к нише) — коммерческие запросы */
const GLOBAL_ARTICLE_TEMPLATES = [
  {
    slug: 'kak-vesti-bazu-klientov-salona-krasoty',
    category: 'client-management',
    title: 'Как вести базу клиентов салона красоты',
    h1: 'Как вести базу клиентов салона красоты',
    articleType: 'howto',
    nicheLabel: 'салона красоты',
  },
  {
    slug: 'crm-dlya-mastera-manikyura-gid',
    category: 'crm',
    title: 'CRM для мастера маникюра: как выбрать и настроить',
    h1: 'CRM для мастера маникюра',
    articleType: 'guide',
    nicheLabel: 'мастера маникюра',
  },
  {
    slug: 'onlajn-zapis-klientov-cherez-telegram',
    category: 'online-booking',
    title: 'Онлайн-запись клиентов через Telegram: полный гид',
    h1: 'Онлайн-запись клиентов через Telegram',
    articleType: 'howto',
    nicheLabel: 'мастеров и салонов',
  },
  {
    slug: 'onlajn-zapis-klientov-cherez-max',
    category: 'online-booking',
    title: 'Онлайн-запись клиентов через MAX',
    h1: 'Онлайн-запись через MAX',
    articleType: 'howto',
    nicheLabel: 'мастеров и салонов',
  },
  {
    slug: 'chem-zamenit-dikidi',
    category: 'compare',
    title: 'Чем заменить DIKIDI в 2026 году',
    h1: 'Чем заменить DIKIDI',
    articleType: 'compare',
    competitor: 'DIKIDI',
    nicheLabel: 'салонов и мастеров',
  },
  {
    slug: 'chem-zamenit-yclients',
    category: 'compare',
    title: 'Чем заменить YCLIENTS: альтернативы для салонов',
    h1: 'Чем заменить YCLIENTS',
    articleType: 'compare',
    competitor: 'YCLIENTS',
    nicheLabel: 'салонов красоты',
  },
  {
    slug: 'chem-zamenit-altegio',
    category: 'compare',
    title: 'Чем заменить Altegio',
    h1: 'Чем заменить Altegio',
    articleType: 'compare',
    competitor: 'Altegio',
    nicheLabel: 'салонов и мастеров',
  },
  {
    slug: 'luchshie-crm-dlya-salona-krasoty',
    category: 'crm',
    title: 'Лучшие CRM для салона красоты в 2026 году',
    h1: 'Лучшие CRM для салона красоты',
    articleType: 'guide',
    nicheLabel: 'салона красоты',
  },
  {
    slug: 'luchshie-servisy-online-zapisi-dlya-masterov',
    category: 'online-booking',
    title: 'Лучшие сервисы онлайн-записи для мастеров',
    h1: 'Лучшие сервисы онлайн-записи для мастеров',
    articleType: 'guide',
    nicheLabel: 'мастеров услуг',
  },
  {
    slug: 'kak-uvelichit-zapisi-s-pomoshchyu-crm',
    category: 'crm',
    title: 'Как увеличить записи с помощью CRM',
    h1: 'Как увеличить записи с помощью CRM',
    articleType: 'guide',
    nicheLabel: 'малого бизнеса',
  },
  {
    slug: 'crm-dlya-salona-krasoty-s-nulya',
    category: 'crm',
    title: 'CRM для салона красоты с нуля: пошаговый план',
    h1: 'CRM для салона красоты с нуля',
    articleType: 'howto',
    nicheLabel: 'салона красоты',
  },
  {
    slug: 'onlajn-zapis-dlya-barbershopa-gid',
    category: 'online-booking',
    title: 'Онлайн-запись для барбершопа: как внедрить',
    h1: 'Онлайн-запись для барбершопа',
    articleType: 'howto',
    nicheLabel: 'барбершопа',
  },
  {
    slug: 'telegram-bot-dlya-zapisi-klientov',
    category: 'online-booking',
    title: 'Telegram-бот для записи клиентов: настройка и сценарии',
    h1: 'Telegram-бот для записи клиентов',
    articleType: 'howto',
    nicheLabel: 'мастеров',
  },
  {
    slug: 'pochemu-klienty-ne-zapisyvayutsya-onlajn',
    category: 'online-booking',
    title: 'Почему клиенты не записываются онлайн и что делать',
    h1: 'Почему клиенты не записываются онлайн',
    articleType: 'opinion',
    nicheLabel: 'салонов и мастеров',
  },
  {
    slug: 'kak-perenesti-bazu-iz-yclients',
    category: 'compare',
    title: 'Как перенести базу клиентов из YCLIENTS',
    h1: 'Как перенести базу из YCLIENTS',
    articleType: 'howto',
    competitor: 'YCLIENTS',
    nicheLabel: 'салонов',
  },
  {
    slug: 'kak-perenesti-bazu-iz-dikidi',
    category: 'compare',
    title: 'Как перенести клиентов из DIKIDI на другой сервис',
    h1: 'Как перенести базу из DIKIDI',
    articleType: 'howto',
    competitor: 'DIKIDI',
    nicheLabel: 'мастеров',
  },
  {
    slug: 'besplatnaya-onlajn-zapis-dlya-masterov',
    category: 'online-booking',
    title: 'Бесплатная онлайн-запись для мастеров: что важно проверить',
    h1: 'Бесплатная онлайн-запись для мастеров',
    articleType: 'guide',
    nicheLabel: 'мастеров',
  },
  {
    slug: 'crm-i-onlajn-zapis-v-odnom-servise',
    category: 'crm',
    title: 'CRM и онлайн-запись в одном сервисе: зачем объединять',
    h1: 'CRM и онлайн-запись в одном сервисе',
    articleType: 'opinion',
    nicheLabel: 'малого бизнеса',
  },
  {
    slug: 'rassylki-klientam-v-telegram-dlya-salona',
    category: 'automation',
    title: 'Рассылки клиентам в Telegram для салона красоты',
    h1: 'Рассылки клиентам в Telegram',
    articleType: 'howto',
    nicheLabel: 'салона красоты',
  },
  {
    slug: 'kak-sokratit-neyavki-klientov',
    category: 'client-management',
    title: 'Как сократить неявки клиентов: 7 рабочих способов',
    h1: 'Как сократить неявки клиентов',
    articleType: 'guide',
    nicheLabel: 'сферы услуг',
  },
];

module.exports = {
  NICHE_ARTICLE_TEMPLATES,
  COMPARE_ARTICLE_COMPETITORS,
  GLOBAL_ARTICLE_TEMPLATES,
};
