/** Каталог целей для внешнего линкбилдинга — 30+ площадок */

const { SITE_URL } = require('./config');

const PLATFORM_LABELS = {
  vc: 'VC.ru',
  dzen: 'Дзен',
  spark: 'СПАРК',
  habr: 'Хабр',
  catalog: 'Каталог',
  partner: 'Партнёр',
  social: 'Соцсеть',
  reddit: 'Reddit',
  producthunt: 'Product Hunt',
  github: 'GitHub',
  press: 'Пресс-релиз',
  pikabu: 'Pikabu',
  indie: 'Indie Hackers',
  slack: 'Slack',
  discord: 'Discord',
  bookmark: 'Закладки',
  forum: 'Форум',
  qa: 'Q&A',
};

function target(path = '/') {
  return path.startsWith('/') ? path : `/${path}`;
}

const EXTERNAL_LINK_CATALOG = [
  // ——— VC.ru ———
  {
    link_key: 'vc-profile',
    platform: 'vc',
    link_type: 'profile',
    title: 'Профиль компании Woner на VC.ru',
    target_path: '/',
    anchor_text: 'Woner.ru — CRM и онлайн-запись для мастеров',
    priority: 10,
    instructions:
      'Создайте профиль компании на vc.ru. В описании — ссылка на woner.ru с UTM. Добавьте логотип, 2–3 скриншота, теги: CRM, бьюти, онлайн-запись.',
    utm_source: 'vc',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },
  {
    link_key: 'vc-article-dikidi',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «Чем заменить DIKIDI в 2026 году»',
    target_path: '/alternativa-dikidi',
    anchor_text: 'альтернатива DIKIDI',
    article_slug: 'chem-zamenit-dikidi',
    priority: 9,
    instructions:
      'Адаптируйте статью из блога (сократите до 4000 знаков). В конце — CTA на woner.ru/alternativa-dikidi. Укажите «Материал подготовлен командой Woner».',
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'alternativa-dikidi',
  },
  {
    link_key: 'vc-article-yclients',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «Чем заменить YCLIENTS»',
    target_path: '/alternativa-yclients',
    anchor_text: 'альтернатива YCLIENTS',
    article_slug: 'chem-zamenit-yclients',
    priority: 9,
    instructions: 'Экспертная колонка с кейсом мастера. Ссылка на лендинг /alternativa-yclients.',
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'alternativa-yclients',
  },
  {
    link_key: 'vc-article-telegram',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «Онлайн-запись через Telegram для салонов»',
    target_path: '/blog/onlajn-zapis-klientov-cherez-telegram',
    anchor_text: 'онлайн-запись через Telegram',
    article_slug: 'onlajn-zapis-klientov-cherez-telegram',
    priority: 8,
    instructions: 'Практический гайд с скриншотами бота. 1–2 ссылки на woner.ru в тексте.',
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'telegram-booking',
  },

  // ——— Дзен ———
  {
    link_key: 'dzen-channel',
    platform: 'dzen',
    link_type: 'profile',
    title: 'Канал Woner в Яндекс Дзен',
    target_path: '/blog',
    anchor_text: 'Woner.ru — блог для мастеров',
    priority: 10,
    instructions:
      'Создайте канал «Woner — CRM для мастеров». Подключите RSS: woner.ru/blog/feed.xml. Публикуйте 2 статьи/нед из блога (автосиндикация).',
    utm_source: 'dzen',
    utm_medium: 'channel',
    utm_campaign: 'blog',
  },
  {
    link_key: 'dzen-article-crm-salon',
    platform: 'dzen',
    link_type: 'article',
    title: 'Дзен: «Лучшие CRM для салона красоты»',
    target_path: '/blog/luchshie-crm-dlya-salona-krasoty',
    anchor_text: 'лучшие CRM для салона красоты',
    article_slug: 'luchshie-crm-dlya-salona-krasoty',
    priority: 8,
    instructions: 'Первая статья вручную + RSS для остальных. Обложка 1200×675.',
    utm_source: 'dzen',
    utm_medium: 'article',
    utm_campaign: 'crm-salon',
  },
  {
    link_key: 'dzen-article-baza-klientov',
    platform: 'dzen',
    link_type: 'article',
    title: 'Дзен: «Как вести базу клиентов салона»',
    target_path: '/blog/kak-vesti-bazu-klientov-salona-krasoty',
    anchor_text: 'база клиентов салона красоты',
    article_slug: 'kak-vesti-bazu-klientov-salona-krasoty',
    priority: 8,
    utm_source: 'dzen',
    utm_medium: 'article',
    utm_campaign: 'client-base',
  },

  // ——— СПАРК ———
  {
    link_key: 'spark-company',
    platform: 'spark',
    link_type: 'profile',
    title: 'Карточка компании в СПАРК (Интерфакс)',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Зарегистрируйте ИП/ООО в СПАРК. Укажите сайт woner.ru в реквизитах. Повышает доверие для B2B-запросов.',
    utm_source: 'spark',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },

  // ——— Хабр ———
  {
    link_key: 'habr-company',
    platform: 'habr',
    link_type: 'profile',
    title: 'Профиль компании на Habr',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Создайте корпоративный аккаунт. Описание: CRM с Telegram/MAX ботами, API для интеграций.',
    utm_source: 'habr',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },
  {
    link_key: 'habr-article-telegram-bot',
    platform: 'habr',
    link_type: 'article',
    title: 'Хабр: «Как мы сделали онлайн-запись через Telegram-бота»',
    target_path: '/blog/onlajn-zapis-klientov-cherez-telegram',
    anchor_text: 'Telegram-бот для записи клиентов',
    priority: 8,
    instructions:
      'Техническая статья: архитектура бота, webhook, UX. Хабр любит код и диаграммы. Ссылка в конце на woner.ru.',
    utm_source: 'habr',
    utm_medium: 'article',
    utm_campaign: 'telegram-tech',
  },
  {
    link_key: 'habr-article-crm-architecture',
    platform: 'habr',
    link_type: 'article',
    title: 'Хабр: «CRM для мастеров: PostgreSQL + React + боты»',
    target_path: '/register',
    anchor_text: 'попробовать Woner бесплатно',
    priority: 6,
    instructions: 'Кейс разработки продукта. Упор на стек и масштабирование до 1000+ мастеров.',
    utm_source: 'habr',
    utm_medium: 'article',
    utm_campaign: 'dev-story',
  },

  // ——— Каталоги и рейтинги ———
  {
    link_key: 'catalog-startpack',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Startpack.ru — каталог SaaS',
    target_path: '/register',
    anchor_text: 'Woner — CRM для мастеров',
    priority: 9,
    instructions: 'Добавьте продукт в каталог startpack.ru. Категория: CRM / Салоны красоты. Скриншоты + описание.',
    utm_source: 'startpack',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-productradar',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Product Radar — запуск продукта',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 8,
    instructions: 'Подайте заявку на productradar.ru. Подготовьте демо-видео 60 сек.',
    utm_source: 'productradar',
    utm_medium: 'catalog',
    utm_campaign: 'launch',
  },
  {
    link_key: 'catalog-crm-index',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'CRM Index / рейтинг CRM для салонов',
    target_path: '/alternativa-yclients',
    anchor_text: 'Woner — альтернатива YCLIENTS',
    priority: 8,
    instructions: 'Найдите рейтинги «CRM для салонов красоты» и подайте заявку на включение.',
    utm_source: 'crmindex',
    utm_medium: 'catalog',
    utm_campaign: 'rating',
  },
  {
    link_key: 'catalog-yandex-business',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Яндекс Бизнес — карточка организации',
    target_path: '/',
    anchor_text: 'Woner.ru — онлайн-запись',
    priority: 9,
    instructions: 'Создайте карточку в Яндекс Бизнес. Укажите сайт, категорию «Программное обеспечение».',
    utm_source: 'yandex_business',
    utm_medium: 'catalog',
    utm_campaign: 'local',
  },
  {
    link_key: 'catalog-2gis',
    platform: 'catalog',
    link_type: 'catalog',
    title: '2ГИС — карточка компании',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Добавьте компанию в 2ГИС с ссылкой на сайт (для локального SEO).',
    utm_source: '2gis',
    utm_medium: 'catalog',
    utm_campaign: 'local',
  },
  {
    link_key: 'catalog-zoon',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Zoon.ru — IT-сервисы',
    target_path: '/register',
    anchor_text: 'CRM Woner',
    priority: 6,
    utm_source: 'zoon',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-irecommend',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'iRecommend — отзывы о CRM',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 6,
    instructions: 'Создайте страницу продукта, попросите 3–5 мастеров оставить отзывы.',
    utm_source: 'irecommend',
    utm_medium: 'catalog',
    utm_campaign: 'reviews',
  },
  {
    link_key: 'catalog-capterra-ru',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Capterra / GetApp (RU) — CRM',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    utm_source: 'capterra',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-beauty-pro',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Каталог «Софт для салонов красоты»',
    target_path: '/otrasli',
    anchor_text: 'CRM для бьюти-индустрии',
    priority: 7,
    instructions: 'Профильные подборки софта для салонов — ищите через «CRM салон красоты каталог».',
    utm_source: 'beauty_catalog',
    utm_medium: 'catalog',
    utm_campaign: 'beauty',
  },

  // ——— Партнёрские блоги ———
  {
    link_key: 'partner-beauty-blog',
    platform: 'partner',
    link_type: 'partner',
    title: 'Гостевой пост в бьюти-блоге',
    target_path: '/blog/kak-vesti-bazu-klientov-salona-krasoty',
    anchor_text: 'как вести базу клиентов',
    priority: 8,
    instructions:
      'Найдите блоги мастеров/школ маникюра (10k+ подписчиков). Предложите гостевой пост или обмен ссылками.',
    utm_source: 'partner_blog',
    utm_medium: 'guest_post',
    utm_campaign: 'beauty',
  },
  {
    link_key: 'partner-school-nails',
    platform: 'partner',
    link_type: 'partner',
    title: 'Партнёрство со школой маникюра',
    target_path: '/register',
    anchor_text: 'бесплатная CRM для выпускников',
    priority: 8,
    instructions: 'Договоритесь со школой: выпускникам — бонус на баланс + ссылка в материалах курса.',
    utm_source: 'nail_school',
    utm_medium: 'partner',
    utm_campaign: 'education',
  },
  {
    link_key: 'partner-salon-franchise',
    platform: 'partner',
    link_type: 'partner',
    title: 'Сеть салонов / франшиза',
    target_path: '/resheniya',
    anchor_text: 'CRM для сети салонов',
    priority: 7,
    instructions: 'Предложите white-label или корпоративный тариф. Взамен — ссылка «Рекомендуемый сервис записи».',
    utm_source: 'salon_network',
    utm_medium: 'partner',
    utm_campaign: 'b2b',
  },
  {
    link_key: 'partner-cosmetics-brand',
    platform: 'partner',
    link_type: 'partner',
    title: 'Бренд косметики — коллаборация',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 6,
    instructions: 'Косметические бренды для мастеров часто ведут блоги. Предложите совместный гайд.',
    utm_source: 'cosmetics_brand',
    utm_medium: 'partner',
    utm_campaign: 'collab',
  },
  {
    link_key: 'partner-telegram-channel',
    platform: 'partner',
    link_type: 'mention',
    title: 'Упоминание в Telegram-канале для мастеров',
    target_path: '/register',
    anchor_text: 'онлайн-запись Woner',
    priority: 8,
    instructions: 'Каналы «маникюр бизнес», «салон красоты» — платное или бартерное размещение.',
    utm_source: 'tg_channel',
    utm_medium: 'mention',
    utm_campaign: 'beauty',
  },

  // ——— Соцсети (sameAs + NAP) ———
  {
    link_key: 'social-vk-group',
    platform: 'social',
    link_type: 'profile',
    title: 'Группа ВКонтакте Woner',
    target_path: '/blog',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Создайте публичную группу. В описании — ссылка. Репосты статей из блога 2×/нед.',
    utm_source: 'vk',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },
  {
    link_key: 'social-telegram-channel',
    platform: 'social',
    link_type: 'profile',
    title: 'Telegram-канал Woner (новости продукта)',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    utm_source: 'telegram',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },
  {
    link_key: 'social-youtube',
    platform: 'social',
    link_type: 'profile',
    title: 'YouTube — обзоры и туториалы',
    target_path: '/register',
    anchor_text: 'попробовать Woner',
    priority: 6,
    instructions: 'Короткие видео «Как настроить запись за 5 минут». Ссылка в описании.',
    utm_source: 'youtube',
    utm_medium: 'social',
    utm_campaign: 'video',
  },

  // ——— Дополнительные VC/Дзен ———
  {
    link_key: 'vc-article-manikyur-crm',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «CRM для мастера маникюра»',
    target_path: '/blog/crm-dlya-mastera-manikyura-gid',
    anchor_text: 'CRM для мастера маникюра',
    article_slug: 'crm-dlya-mastera-manikyura-gid',
    priority: 8,
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'manicure-crm',
  },
  {
    link_key: 'dzen-article-manikyur',
    platform: 'dzen',
    link_type: 'article',
    title: 'Дзен: «CRM для маникюра без DIKIDI»',
    target_path: '/alternativa-dikidi',
    anchor_text: 'замена DIKIDI',
    article_slug: 'chem-zamenit-dikidi',
    priority: 7,
    utm_source: 'dzen',
    utm_medium: 'article',
    utm_campaign: 'dikidi',
  },

  // ============ АВТО-САБМИТ: API площадки ============

  // ——— Reddit (API) ———
  {
    link_key: 'reddit-r-saas',
    platform: 'reddit',
    link_type: 'post',
    title: 'Reddit r/SaaS — пост про Woner.ru',
    target_path: '/',
    anchor_text: 'woner.ru — CRM и онлайн-запись для мастеров',
    priority: 8,
    auto_submit: 'api',
    api_endpoint: 'https://oauth.reddit.com/api/submit',
    submission_url: 'https://www.reddit.com/r/SaaS/submit',
    audience_size: 250000,
    domain_rating: 91,
    requires_review: false,
    tags: ['saas', 'crm', 'api'],
    instructions:
      'Авто-пост через Reddit API (OAuth2). Заголовок «Show HN: CRM для мастеров услуг с Telegram/MAX ботами». Правила r/SaaS: self-promotion только в пятницу, 1× в неделю.',
    content_template:
      'Title: Show HN: Woner.ru — CRM and online booking for service pros (with Telegram bot)\n\nWe built woner.ru to help solo beauty/health masters run their booking, CRM and reminders without Excel.\n\nKey features:\n- Online booking page in 5 min (no-code)\n- Telegram & MAX bot for instant confirmations\n- Client base + reminders (cuts no-shows by 40%)\n- Free up to 30 bookings/month\n- Built for Russia/CIS (Russian-language UI, MAX messenger integration)\n\nLooking for feedback from SaaS founders and CRM builders. AMA!\n\n{{tracked_url}}',
    utm_source: 'reddit',
    utm_medium: 'post',
    utm_campaign: 'show-saas',
  },
  {
    link_key: 'reddit-r-startups',
    platform: 'reddit',
    link_type: 'post',
    title: 'Reddit r/startups — пост про запуск Woner',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    auto_submit: 'api',
    api_endpoint: 'https://oauth.reddit.com/api/submit',
    submission_url: 'https://www.reddit.com/r/startups/submit',
    audience_size: 1200000,
    domain_rating: 91,
    requires_review: false,
    tags: ['startups', 'launch', 'saas'],
    content_template:
      'Title: We launched Woner.ru — CRM for solo service pros (booking + Telegram + reminders)\n\nAfter 6 months in beta with 50+ masters, we are opening Woner.ru to public.\n\nWhy this niche: 80% of Russian beauty/health masters still use notebooks and WhatsApp groups for booking. We automate the routine and cut no-shows.\n\nTech: Node.js + React + PostgreSQL, MAX messenger integration, Telegram Bot API.\n\nFree up to 30 bookings/mo. Would love your feedback.\n\n{{tracked_url}}',
    utm_source: 'reddit',
    utm_medium: 'post',
    utm_campaign: 'launch',
  },
  {
    link_key: 'reddit-r-indiehackers',
    platform: 'reddit',
    link_type: 'post',
    title: 'Reddit r/IndieHackers — кейс Woner',
    target_path: '/blog',
    anchor_text: 'woner.ru blog',
    priority: 6,
    auto_submit: 'api',
    api_endpoint: 'https://oauth.reddit.com/api/submit',
    submission_url: 'https://www.reddit.com/r/IndieHackers/submit',
    audience_size: 320000,
    domain_rating: 91,
    requires_review: false,
    tags: ['indie', 'milestone'],
    content_template:
      'Title: [Milestone] Woner.ru — 50 paying masters in 6 months, fully bootstrapped\n\nQuick story:\n- Launched beta Jan 2026\n- 50 paying masters in beauty/health niche\n- $0 paid acquisition, 100% organic SEO + word-of-mouth\n- Stack: Node.js + React + PostgreSQL\n\nWhat worked: programmatic SEO (2500+ geo landing pages) and Telegram-native UX.\n\nLessons learned and numbers inside.\n\n{{tracked_url}}',
    utm_source: 'reddit',
    utm_medium: 'post',
    utm_campaign: 'indie-milestone',
  },

  // ——— Product Hunt (GraphQL API) ———
  {
    link_key: 'producthunt-launch',
    platform: 'producthunt',
    link_type: 'launch',
    title: 'Product Hunt — запуск Woner.ru',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 10,
    auto_submit: 'api',
    api_endpoint: 'https://api.producthunt.com/v2/api/graphql',
    submission_url: 'https://www.producthunt.com/posts/new',
    audience_size: 5000000,
    domain_rating: 92,
    requires_review: true,
    tags: ['launch', 'saas', 'productivity'],
    content_template:
      'Name: Woner.ru\nTagline: Online booking & CRM for solo beauty and health pros\nDescription: Free online booking page + Telegram bot + CRM for solo masters. Built for Russia/CIS, supports MAX messenger. Setup in 5 minutes, no credit card.\nTopics: Productivity, SaaS, CRM, Beauty\nMaker: {{site_name}}',
    utm_source: 'producthunt',
    utm_medium: 'launch',
    utm_campaign: 'ph-launch',
  },

  // ——— GitHub Profile (README) ———
  {
    link_key: 'github-profile',
    platform: 'github',
    link_type: 'profile',
    title: 'GitHub — корпоративный профиль woner',
    target_path: '/',
    anchor_text: 'github.com/woner',
    priority: 8,
    auto_submit: 'api',
    api_endpoint: 'https://api.github.com/user/repos',
    submission_url: 'https://github.com/settings/profile',
    audience_size: 100000000,
    domain_rating: 96,
    requires_review: false,
    tags: ['profile', 'open-source'],
    instructions:
      'Создать организацию github.com/woner с README в profile-репозитории. Ссылка на woner.ru в bio и README.',
    content_template:
      '# Woner\n\n🚀 CRM + online booking + Telegram bot for solo beauty/health pros.\n\n🇷🇺 Built for Russia/CIS — supports MAX messenger.\n\n🌐 woner.ru',
    utm_source: 'github',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },

  // ——— Press-feed (Пресс-релизы через API) ———
  {
    link_key: 'press-feed-launch',
    platform: 'press',
    link_type: 'release',
    title: 'Пресс-релиз на Press-feed.ru: запуск Woner.ru',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 9,
    auto_submit: 'api',
    api_endpoint: 'https://press-feed.ru/api/v1/releases',
    submission_url: 'https://press-feed.ru/add',
    audience_size: 800000,
    domain_rating: 64,
    requires_review: true,
    tags: ['press-release', 'launch'],
    instructions:
      'Авто-публикация пресс-релиза через Press-feed API. Обязательно указать контакт и email.',
    content_template:
      'Заголовок: Woner.ru открыл бесплатный онлайн-сервис для мастеров услуг\n\nАнонс: Сервис woner.ru объявил о публичном запуске CRM с онлайн-записью и Telegram-ботом. Целевая аудитория — частные мастера бьюти и здоровья, которые до сих пор ведут запись в блокноте.\n\nКлючевые факты:\n- Бесплатный тариф до 30 записей в месяц\n- Telegram + MAX бот для подтверждений\n- Настройка за 5 минут без программистов\n- Хранение данных в РФ (152-ФЗ)\n\nСайт: {{tracked_url}}\n\nКонтакт: {{contact_email}}',
    utm_source: 'pressfeed',
    utm_medium: 'release',
    utm_campaign: 'launch',
  },
  {
    link_key: 'press-interfax',
    platform: 'press',
    link_type: 'release',
    title: 'Пресс-релиз на Интерфакс через сервис-агрегатор',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    auto_submit: 'manual',
    submission_url: 'https://www.interfax.ru/press-releases/',
    audience_size: 5000000,
    domain_rating: 88,
    requires_review: true,
    tags: ['press-release', 'b2b'],
    instructions:
      'Через платный сервис press-releases.ru или напрямую через Интерфакс. Стоимость ~3000-15000 ₽ за размещение.',
    utm_source: 'interfax',
    utm_medium: 'release',
    utm_campaign: 'b2b-launch',
  },

  // ——— Pikabu (свой блог) ———
  {
    link_key: 'pikabu-community',
    platform: 'pikabu',
    link_type: 'post',
    title: 'Pikabu — пост в сообществе «Бизнес»',
    target_path: '/blog/chem-zamenit-dikidi',
    anchor_text: 'чем заменить DIKIDI в 2026',
    priority: 6,
    auto_submit: 'api',
    api_endpoint: 'https://pikabu.ru/page/api',
    submission_url: 'https://pikabu.ru/add',
    audience_size: 15000000,
    domain_rating: 87,
    requires_review: true,
    tags: ['community', 'beauty', 'business'],
    instructions:
      'Публикация через Pikabu API в сообщество «Бизнес» или «IT». Самоспам запрещён — нужна польза.',
    content_template:
      'Заголовок: Чем заменить DIKIDI в 2026 году: разбор 5 альтернатив\n\nТекст: я мастер маникюра и пользовался DIKIDI 3 года. Когда в 2025 выкатили новый тариф — стало невыгодно. Перебрал 5 альтернатив, делюсь опытом: {{tracked_url}}',
    utm_source: 'pikabu',
    utm_medium: 'post',
    utm_campaign: 'dikidi-alt',
  },

  // ——— Indie Hackers (сабмит продукта) ———
  {
    link_key: 'indiehackers-product',
    platform: 'indie',
    link_type: 'product',
    title: 'Indie Hackers — карточка продукта Woner',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 8,
    auto_submit: 'api',
    api_endpoint: 'https://www.indiehackers.com/api',
    submission_url: 'https://www.indiehackers.com/products/new',
    audience_size: 600000,
    domain_rating: 79,
    requires_review: true,
    tags: ['indie', 'product-launch'],
    instructions:
      'IndieHackers принимает продукты через форму. После одобрения появляется постоянная страница.',
    content_template:
      'Name: Woner.ru\nTagline: Online booking + CRM + Telegram bot for solo service pros\nDescription: Woner.ru is a free booking and CRM platform for solo beauty and health professionals in Russia/CIS. Built with Node.js, React, PostgreSQL. Integrated with Telegram Bot API and MAX messenger. Free up to 30 bookings/mo.',
    utm_source: 'indiehackers',
    utm_medium: 'product',
    utm_campaign: 'launch',
  },

  // ——— Toster / Habr Q&A ———
  {
    link_key: 'toster-qa',
    platform: 'qa',
    link_type: 'answer',
    title: 'Toster.ru — ответы на вопросы про CRM',
    target_path: '/blog',
    anchor_text: 'наш опыт',
    priority: 5,
    auto_submit: 'manual',
    submission_url: 'https://qna.habr.com/',
    audience_size: 800000,
    domain_rating: 85,
    requires_review: false,
    tags: ['qa', 'expert'],
    instructions:
      'Отвечать на вопросы в Toster про выбор CRM для салона. В ответе давать экспертный комментарий и ссылку на woner.ru как на один из вариантов (не реклама, а реальный ответ).',
    utm_source: 'toster',
    utm_medium: 'answer',
    utm_campaign: 'expert',
  },

  // ——— Slack/Discord сообщества ———
  {
    link_key: 'slack-saas-ru',
    platform: 'slack',
    link_type: 'post',
    title: 'Slack #SaaS-EN — анонс Woner',
    target_path: '/',
    anchor_text: 'woner.ru',
    priority: 5,
    auto_submit: 'webhook',
    api_endpoint: 'https://hooks.slack.com/services/...',
    submission_url: 'https://slack.com/',
    audience_size: 5000,
    domain_rating: 0,
    requires_review: false,
    tags: ['community', 'saas'],
    instructions:
      'Если есть webhook для SaaS-сообществ, постить через webhook. Иначе — ручной пост.',
    content_template:
      'Hey! Мы запустили woner.ru — CRM + онлайн-запись + Telegram/MAX-бот для мастеров бьюти. Бесплатно до 30 записей в месяц. Буду рад фидбэку: {{tracked_url}}',
    utm_source: 'slack',
    utm_medium: 'post',
    utm_campaign: 'launch',
  },

  // ——— Hacker News (Show HN) ———
  {
    link_key: 'hackernews-show',
    platform: 'reddit',
    link_type: 'post',
    title: 'Hacker News — Show HN: Woner',
    target_path: '/',
    anchor_text: 'woner.ru',
    priority: 9,
    auto_submit: 'api',
    api_endpoint: 'https://hacker-news.firebaseio.com/v0/item',
    submission_url: 'https://news.ycombinator.com/submit',
    audience_size: 5000000,
    domain_rating: 90,
    requires_review: false,
    tags: ['show-hn', 'launch'],
    instructions:
      'Через Hacker News API нельзя постить — только через форму submit. Делаем вручную в прайм-тайм (пн-ср, 9:00-11:00 EST).',
    content_template:
      'Title: Show HN: Woner.ru – CRM with Telegram/MAX bot for solo beauty pros\n\nI built Woner.ru to replace notebooks and WhatsApp groups for solo beauty/health masters in Russia. Free up to 30 bookings/mo, integrated with Telegram and MAX (Russian messenger).\n\nHappy to answer any questions about the stack or business model.',
    utm_source: 'hackernews',
    utm_medium: 'show-hn',
    utm_campaign: 'launch',
  },

  // ——— Slashdot ———
  {
    link_key: 'slashdot-story',
    platform: 'forum',
    link_type: 'story',
    title: 'Slashdot — сабмит истории про Woner',
    target_path: '/',
    anchor_text: 'woner.ru',
    priority: 5,
    auto_submit: 'form',
    submission_url: 'https://slashdot.org/submit',
    audience_size: 1500000,
    domain_rating: 89,
    requires_review: true,
    tags: ['tech', 'news'],
    instructions:
      'Slashdot требует редакционного одобрения. Истории про стартап с Telegram/MAX обычно не проходят модерацию (off-topic), но попробовать стоит.',
    utm_source: 'slashdot',
    utm_medium: 'story',
    utm_campaign: 'launch',
  },

  // ——— Социальные закладки (RSS/формы) ———
  {
    link_key: 'bookmark-pocket',
    platform: 'bookmark',
    link_type: 'save',
    title: 'Pocket — сохранить статью блога',
    target_path: '/blog/chem-zamenit-dikidi',
    anchor_text: 'Чем заменить DIKIDI',
    priority: 4,
    auto_submit: 'api',
    api_endpoint: 'https://getpocket.com/v3/add',
    submission_url: 'https://getpocket.com/',
    audience_size: 30000000,
    domain_rating: 92,
    requires_review: false,
    tags: ['bookmark', 'seo'],
    instructions: 'Сохранить статью через Pocket API. Учётная запись Woner для брендового присутствия.',
    utm_source: 'pocket',
    utm_medium: 'save',
    utm_campaign: 'blog',
  },
  {
    link_key: 'bookmark-raindrop',
    platform: 'bookmark',
    link_type: 'save',
    title: 'Raindrop.io — коллекция статей блога',
    target_path: '/blog',
    anchor_text: 'Woner блог',
    priority: 4,
    auto_submit: 'api',
    api_endpoint: 'https://api.raindrop.io/rest/v1/raindrops',
    submission_url: 'https://raindrop.io/',
    audience_size: 1000000,
    domain_rating: 76,
    requires_review: false,
    tags: ['bookmark', 'seo'],
    instructions: 'Сохранить статьи блога в публичную коллекцию.',
    utm_source: 'raindrop',
    utm_medium: 'save',
    utm_campaign: 'blog',
  },

  // ——— Diigo (социальные закладки для SEO) ———
  {
    link_key: 'bookmark-diigo',
    platform: 'bookmark',
    link_type: 'save',
    title: 'Diigo — сохранение статей блога',
    target_path: '/blog',
    anchor_text: 'Woner блог',
    priority: 4,
    auto_submit: 'api',
    api_endpoint: 'https://secure.diigo.com/api/v2/bookmarks',
    submission_url: 'https://www.diigo.com/',
    audience_size: 800000,
    domain_rating: 78,
    requires_review: false,
    tags: ['bookmark', 'seo'],
    instructions: 'Diigo — старейший сервис закладок, dofollow-ссылки работают.',
    utm_source: 'diigo',
    utm_medium: 'save',
    utm_campaign: 'blog',
  },
  {
    link_key: 'bookmark-delicious',
    platform: 'bookmark',
    link_type: 'save',
    title: 'Delicious — сохранение статей',
    target_path: '/blog',
    anchor_text: 'Woner блог',
    priority: 3,
    auto_submit: 'api',
    api_endpoint: 'https://api.delicious.com/v1/posts/add',
    submission_url: 'https://delicious.com/',
    audience_size: 500000,
    domain_rating: 92,
    requires_review: false,
    tags: ['bookmark', 'seo'],
    instructions: 'Delicious — старейший, высокий DR.',
    utm_source: 'delicious',
    utm_medium: 'save',
    utm_campaign: 'blog',
  },

  // ——— StumbleUpon (Mix) ———
  {
    link_key: 'bookmark-mix',
    platform: 'bookmark',
    link_type: 'save',
    title: 'Mix.com (StumbleUpon) — сохранить статью',
    target_path: '/blog',
    anchor_text: 'Woner',
    priority: 3,
    auto_submit: 'api',
    api_endpoint: 'https://mix.com/api/v1/bookmarks',
    submission_url: 'https://mix.com/',
    audience_size: 2000000,
    domain_rating: 88,
    requires_review: false,
    tags: ['bookmark', 'discovery'],
    instructions: 'Mix — наследник StumbleUpon, открытый API.',
    utm_source: 'mix',
    utm_medium: 'save',
    utm_campaign: 'blog',
  },

  // ——— Каталоги SaaS ———
  {
    link_key: 'catalog-saashub',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'SaaSHub — каталог SaaS',
    target_path: '/register',
    anchor_text: 'Woner — CRM для мастеров',
    priority: 8,
    auto_submit: 'form',
    submission_url: 'https://www.saashub.com/startup/submit',
    audience_size: 5000000,
    domain_rating: 81,
    requires_review: true,
    tags: ['saas-catalog', 'discovery'],
    instructions: 'SaaSHub — крупнейший каталог SaaS. Сабмит бесплатен, проходит модерацию за 1-3 дня.',
    utm_source: 'saashub',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-alternativeto',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'AlternativeTo — карточка продукта',
    target_path: '/alternativa-dikidi',
    anchor_text: 'альтернатива DIKIDI',
    priority: 8,
    auto_submit: 'form',
    submission_url: 'https://alternativeto.net/AddSoftware',
    audience_size: 15000000,
    domain_rating: 78,
    requires_review: true,
    tags: ['alternatives', 'discovery'],
    instructions: 'AlternativeTo — крупнейший каталог альтернатив. Указываем как альтернативу DIKIDI, YCLIENTS, Altegio.',
    utm_source: 'alternativeto',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-crozdesk',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Crozdesk — каталог бизнес-PO',
    target_path: '/register',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'form',
    submission_url: 'https://crozdesk.com/submit-software',
    audience_size: 2000000,
    domain_rating: 72,
    requires_review: true,
    tags: ['catalog'],
    instructions: 'Crozdesk — каталог бизнес-PO с обзорами.',
    utm_source: 'crozdesk',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-g2',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'G2 — карточка продукта',
    target_path: '/register',
    anchor_text: 'Woner',
    priority: 9,
    auto_submit: 'form',
    submission_url: 'https://www.g2.com/products/new',
    audience_size: 80000000,
    domain_rating: 94,
    requires_review: true,
    tags: ['reviews', 'b2b'],
    instructions: 'G2 — крупнейший B2B-каталог. Требует регистрации компании и проходит строгую модерацию.',
    utm_source: 'g2',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-softwareadvice',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Software Advice — каталог',
    target_path: '/register',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'form',
    submission_url: 'https://www.softwareadvice.com/',
    audience_size: 5000000,
    domain_rating: 80,
    requires_review: true,
    tags: ['catalog'],
    instructions: 'Software Advice — один из старейших B2B-каталогов.',
    utm_source: 'softwareadvice',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-sourceforge',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'SourceForge — каталог PO',
    target_path: '/register',
    anchor_text: 'Woner',
    priority: 6,
    auto_submit: 'form',
    submission_url: 'https://sourceforge.net/software/new/',
    audience_size: 30000000,
    domain_rating: 91,
    requires_review: true,
    tags: ['catalog', 'opensource'],
    instructions: 'SourceForge — старейший каталог open-source и бизнес-PO.',
    utm_source: 'sourceforge',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-flippa',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Crunchbase — карточка компании',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 6,
    auto_submit: 'form',
    submission_url: 'https://www.crunchbase.com/add-company',
    audience_size: 12000000,
    domain_rating: 93,
    requires_review: true,
    tags: ['startup-database'],
    instructions: 'Crunchbase — база данных стартапов. Платный план для подробной карточки (Basic $29/mo).',
    utm_source: 'crunchbase',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-betaliist',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'BetaList — карточка продукта',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 8,
    auto_submit: 'form',
    submission_url: 'https://betalist.com/submit',
    audience_size: 500000,
    domain_rating: 76,
    requires_review: true,
    tags: ['launch', 'beta'],
    instructions: 'BetaList — каталог бета-версий и запусков. Дата запуска назначается после одобрения.',
    utm_source: 'betalist',
    utm_medium: 'catalog',
    utm_campaign: 'launch',
  },
  {
    link_key: 'catalog-betapage',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'BetaPage — каталог бета-версий',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'form',
    submission_url: 'https://betapage.co/submit-a-startup',
    audience_size: 200000,
    domain_rating: 64,
    requires_review: true,
    tags: ['launch', 'beta'],
    utm_source: 'betapage',
    utm_medium: 'catalog',
    utm_campaign: 'launch',
  },
  {
    link_key: 'catalog-everything-saas',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'EverythingSaaS — каталог SaaS',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'form',
    submission_url: 'https://everythingsaas.pro/submit',
    audience_size: 100000,
    domain_rating: 50,
    requires_review: true,
    tags: ['catalog'],
    utm_source: 'everythingsaas',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-saas-finder',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'SaaSFinder — каталог',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'form',
    submission_url: 'https://saasfinder.com/submit',
    audience_size: 50000,
    domain_rating: 40,
    requires_review: true,
    tags: ['catalog'],
    utm_source: 'saasfinder',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },

  // ——— Open Source рейтинги ———
  {
    link_key: 'catalog-opencrunch',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'OpenCrunch — база стартапов',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'form',
    submission_url: 'https://opencrunch.io/',
    audience_size: 100000,
    domain_rating: 45,
    requires_review: true,
    tags: ['startup-database'],
    utm_source: 'opencrunch',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },

  // ——— Crunchbase Free ———
  {
    link_key: 'catalog-producthunt-maker',
    platform: 'producthunt',
    link_type: 'profile',
    title: 'Product Hunt — Maker Profile',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'api',
    api_endpoint: 'https://api.producthunt.com/v2/api/graphql',
    submission_url: 'https://www.producthunt.com/makers',
    audience_size: 5000000,
    domain_rating: 92,
    requires_review: false,
    tags: ['maker-profile'],
    instructions: 'Создать maker-профиль на Product Hunt, привязать к продукту.',
    utm_source: 'producthunt',
    utm_medium: 'maker-profile',
    utm_campaign: 'brand',
  },

  // ——— AngelList / Wellfound ———
  {
    link_key: 'catalog-wellfound',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Wellfound (AngelList) — карточка стартапа',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'form',
    submission_url: 'https://wellfound.com/company/new',
    audience_size: 8000000,
    domain_rating: 87,
    requires_review: true,
    tags: ['startups', 'hiring'],
    instructions: 'Wellfound — для найма и инвестиций. Можно добавить компанию бесплатно.',
    utm_source: 'wellfound',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },

  // ——— F6S (Founders Network) ———
  {
    link_key: 'catalog-f6s',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'F6S — стартап-каталог',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'form',
    submission_url: 'https://www.f6s.com/company-submit',
    audience_size: 1000000,
    domain_rating: 70,
    requires_review: true,
    tags: ['startup-database'],
    utm_source: 'f6s',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },

  // ——— Trustpilot ———
  {
    link_key: 'catalog-trustpilot',
    platform: 'catalog',
    link_type: 'profile',
    title: 'Trustpilot — страница компании',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    auto_submit: 'form',
    submission_url: 'https://www.trustpilot.com/evaluate/woner.ru',
    audience_size: 50000000,
    domain_rating: 94,
    requires_review: false,
    tags: ['reviews'],
    instructions: 'Trustpilot — крупнейший сервис отзывов. Нужно заявить компанию и пригласить клиентов оставить отзывы.',
    utm_source: 'trustpilot',
    utm_medium: 'profile',
    utm_campaign: 'reviews',
  },

  // ——— Яндекс.Маркет (если можно для SaaS) ———
  {
    link_key: 'catalog-yandex-market',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Яндекс.Маркет — каталог PO',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 6,
    auto_submit: 'manual',
    submission_url: 'https://partner.market.yandex.ru/',
    audience_size: 20000000,
    domain_rating: 95,
    requires_review: true,
    tags: ['yandex', 'catalog'],
    instructions: 'Программы для SaaS на Яндекс.Маркет ограничены, но можно попробовать через партнёрскую программу.',
    utm_source: 'yandex_market',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },

  // ——— Отзовики ———
  {
    link_key: 'catalog-otzovik',
    platform: 'catalog',
    link_type: 'profile',
    title: 'Отзовик — страница о Woner',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'manual',
    submission_url: 'https://otzovik.com/',
    audience_size: 8000000,
    domain_rating: 80,
    requires_review: true,
    tags: ['reviews', 'ru'],
    instructions: 'Отзовик — крупный RU-отзовик. Завести брендовую страницу и попросить клиентов.',
    utm_source: 'otzovik',
    utm_medium: 'profile',
    utm_campaign: 'reviews',
  },

  // ——— VC.ru комьюнити ———
  {
    link_key: 'vc-comments-expert',
    platform: 'vc',
    link_type: 'comment',
    title: 'VC.ru — экспертные комментарии',
    target_path: '/blog',
    anchor_text: 'наш опыт',
    priority: 6,
    auto_submit: 'manual',
    submission_url: 'https://vc.ru/',
    audience_size: 15000000,
    domain_rating: 85,
    requires_review: false,
    tags: ['expert', 'comments'],
    instructions: 'Подписка на VC.ru, ежедневные экспертные комментарии под постами про CRM, запись, бьюти-бизнес.',
    utm_source: 'vc',
    utm_medium: 'comment',
    utm_campaign: 'expert',
  },

  // ——— Quora ———
  {
    link_key: 'quora-answers',
    platform: 'qa',
    link_type: 'answer',
    title: 'Quora — ответы про CRM для мастеров',
    target_path: '/blog/chem-zamenit-dikidi',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'manual',
    submission_url: 'https://www.quora.com/',
    audience_size: 300000000,
    domain_rating: 93,
    requires_review: false,
    tags: ['qa', 'expert'],
    instructions: 'Отвечать на вопросы в Quora про booking CRM, salon management. Ссылка в bio, не в самом ответе.',
    utm_source: 'quora',
    utm_medium: 'answer',
    utm_campaign: 'expert',
  },

  // ——— Medium (своя публикация) ———
  {
    link_key: 'medium-publication',
    platform: 'catalog',
    link_type: 'article',
    title: 'Medium — публикация Wonersaas',
    target_path: '/blog/chem-zamenit-dikidi',
    anchor_text: 'Woner',
    priority: 6,
    auto_submit: 'api',
    api_endpoint: 'https://api.medium.com/v1/users/me/posts',
    submission_url: 'https://medium.com/',
    audience_size: 100000000,
    domain_rating: 95,
    requires_review: false,
    tags: ['medium', 'syndication'],
    instructions: 'Создать publication "Woner", публиковать статьи из блога через Medium API.',
    content_template: '{{article_content}}\n\nOriginally posted at {{tracked_url}}',
    utm_source: 'medium',
    utm_medium: 'article',
    utm_campaign: 'syndication',
  },

  // ——— LinkedIn (через API) ———
  {
    link_key: 'linkedin-company',
    platform: 'social',
    link_type: 'profile',
    title: 'LinkedIn — страница компании Woner',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'api',
    api_endpoint: 'https://api.linkedin.com/v2/organizations',
    submission_url: 'https://www.linkedin.com/company/setup/new/',
    audience_size: 900000000,
    domain_rating: 98,
    requires_review: true,
    tags: ['linkedin', 'b2b'],
    instructions: 'Создать company page на LinkedIn, постить обновления продукта.',
    utm_source: 'linkedin',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },

  // ——— X/Twitter ———
  {
    link_key: 'twitter-profile',
    platform: 'social',
    link_type: 'profile',
    title: 'X (Twitter) — @woner_ru',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'api',
    api_endpoint: 'https://api.twitter.com/2/users/me',
    submission_url: 'https://twitter.com/i/flow/signup',
    audience_size: 500000000,
    domain_rating: 94,
    requires_review: false,
    tags: ['twitter', 'social'],
    instructions: 'Создать @woner_ru, публиковать фичи и кейсы через Twitter API v2.',
    utm_source: 'twitter',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },

  // ——— Pinterest ———
  {
    link_key: 'pinterest-board',
    platform: 'social',
    link_type: 'profile',
    title: 'Pinterest — доска Wonersaas',
    target_path: '/blog',
    anchor_text: 'Woner',
    priority: 4,
    auto_submit: 'api',
    api_endpoint: 'https://api.pinterest.com/v5/boards',
    submission_url: 'https://www.pinterest.com/',
    audience_size: 400000000,
    domain_rating: 93,
    requires_review: false,
    tags: ['pinterest', 'discovery'],
    instructions: 'Pinterest используется для discovery. Закрепляем ссылки на статьи блога с обложками.',
    utm_source: 'pinterest',
    utm_medium: 'board',
    utm_campaign: 'blog',
  },

  // ——— Telegram-канал (через Bot API) ———
  {
    link_key: 'telegram-bot-channel',
    platform: 'social',
    link_type: 'profile',
    title: 'Telegram-канал @woner_official',
    target_path: '/blog',
    anchor_text: 'Woner',
    priority: 8,
    auto_submit: 'api',
    api_endpoint: 'https://api.telegram.org/bot{token}/sendMessage',
    submission_url: 'https://t.me/woner_official',
    audience_size: 100000,
    domain_rating: 0,
    requires_review: false,
    tags: ['telegram', 'social'],
    instructions: 'Telegram-канал. Автопубликация через бот: статьи блога + кейсы клиентов.',
    utm_source: 'telegram',
    utm_medium: 'channel',
    utm_campaign: 'blog',
  },

  // ——— VK группа (через API) ———
  {
    link_key: 'vk-group',
    platform: 'social',
    link_type: 'profile',
    title: 'ВКонтакте — паблик Woner',
    target_path: '/blog',
    anchor_text: 'Woner',
    priority: 7,
    auto_submit: 'api',
    api_endpoint: 'https://api.vk.com/method/wall.post',
    submission_url: 'https://vk.com/woner',
    audience_size: 100000000,
    domain_rating: 96,
    requires_review: false,
    tags: ['vk', 'social', 'ru'],
    instructions: 'VK-паблик. Автопубликация статей блога через VK API.',
    utm_source: 'vk',
    utm_medium: 'social',
    utm_campaign: 'blog',
  },

  // ——— Tumblr ———
  {
    link_key: 'tumblr-blog',
    platform: 'social',
    link_type: 'profile',
    title: 'Tumblr — блог Woner',
    target_path: '/blog',
    anchor_text: 'Woner',
    priority: 3,
    auto_submit: 'api',
    api_endpoint: 'https://api.tumblr.com/v2/blog/woner.tumblr.com/post',
    submission_url: 'https://www.tumblr.com/',
    audience_size: 200000000,
    domain_rating: 92,
    requires_review: false,
    tags: ['tumblr', 'syndication'],
    instructions: 'Tumblr ещё жив, высокий DR. Синдицируем статьи блога.',
    utm_source: 'tumblr',
    utm_medium: 'social',
    utm_campaign: 'blog',
  },

  // ——— Gravatar ———
  {
    link_key: 'gravatar-profile',
    platform: 'catalog',
    link_type: 'profile',
    title: 'Gravatar — профиль Woner',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'api',
    api_endpoint: 'https://en.gravatar.com/accounts',
    submission_url: 'https://en.gravatar.com/',
    audience_size: 50000000,
    domain_rating: 91,
    requires_review: false,
    tags: ['profile'],
    instructions: 'Профиль Woner на Gravatar. Используется WordPress/Jetpack комментариями.',
    utm_source: 'gravatar',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },

  // ——— About.me ———
  {
    link_key: 'about-me',
    platform: 'catalog',
    link_type: 'profile',
    title: 'About.me — карточка основателя',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 4,
    auto_submit: 'manual',
    submission_url: 'https://about.me/new',
    audience_size: 5000000,
    domain_rating: 86,
    requires_review: false,
    tags: ['profile', 'personal'],
    instructions: 'Страница основателя на about.me с ссылкой на woner.ru.',
    utm_source: 'aboutme',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },

  // ——— Mastodon (federated) ———
  {
    link_key: 'mastodon-profile',
    platform: 'social',
    link_type: 'profile',
    title: 'Mastodon — аккаунт @woner',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 4,
    auto_submit: 'api',
    api_endpoint: 'https://mastodon.social/api/v1/statuses',
    submission_url: 'https://mastodon.social/',
    audience_size: 10000000,
    domain_rating: 86,
    requires_review: false,
    tags: ['mastodon', 'social'],
    instructions: 'Mastodon — децентрализованная соцсеть. Создать аккаунт через API.',
    utm_source: 'mastodon',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },

  // ——— Threads (Meta) ———
  {
    link_key: 'threads-profile',
    platform: 'social',
    link_type: 'profile',
    title: 'Threads — @woner',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 5,
    auto_submit: 'api',
    api_endpoint: 'https://graph.threads.net/v1.0/me/threads',
    submission_url: 'https://www.threads.net/',
    audience_size: 200000000,
    domain_rating: 92,
    requires_review: false,
    tags: ['threads', 'social'],
    instructions: 'Threads от Meta. Автопост через Threads API.',
    utm_source: 'threads',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },

  // ——— Diaspora ———
  {
    link_key: 'diaspora-profile',
    platform: 'social',
    link_type: 'profile',
    title: 'Diaspora* — профиль Woner',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 2,
    auto_submit: 'manual',
    submission_url: 'https://diasporafoundation.org/',
    audience_size: 1000000,
    domain_rating: 70,
    requires_review: false,
    tags: ['diaspora', 'social'],
    utm_source: 'diaspora',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },

  // ——— Bluesky ———
  {
    link_key: 'bluesky-profile',
    platform: 'social',
    link_type: 'profile',
    title: 'Bluesky — @woner.bsky.social',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 4,
    auto_submit: 'api',
    api_endpoint: 'https://public.api.bsky.app/xrpc/com.atproto.repo.createRecord',
    submission_url: 'https://bsky.app/',
    audience_size: 30000000,
    domain_rating: 85,
    requires_review: false,
    tags: ['bluesky', 'social'],
    instructions: 'Bluesky — новая соцсеть. AT Protocol API для автопостинга.',
    utm_source: 'bluesky',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },

  // ——— XDA Developers (форум) ———
  {
    link_key: 'forum-xda',
    platform: 'forum',
    link_type: 'post',
    title: 'XDA Developers — пост (off-topic не подходит)',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 1,
    auto_submit: 'manual',
    submission_url: 'https://forum.xda-developers.com/',
    audience_size: 5000000,
    domain_rating: 80,
    requires_review: true,
    tags: ['forum', 'tech'],
    instructions: 'XDA — только Android-разработка, нам не подходит. Пропускаем.',
    utm_source: 'xda',
    utm_medium: 'forum',
    utm_campaign: 'launch',
  },
];

function buildTrackedUrl(targetPath, { utm_source, utm_medium, utm_campaign } = {}) {
  const base = `${SITE_URL}${target(targetPath)}`;
  const params = new URLSearchParams();
  if (utm_source) params.set('utm_source', utm_source);
  if (utm_medium) params.set('utm_medium', utm_medium);
  if (utm_campaign) params.set('utm_campaign', utm_campaign);
  const qs = params.toString();
  return qs ? `${base}?${qs}` : base;
}

module.exports = {
  EXTERNAL_LINK_CATALOG,
  PLATFORM_LABELS,
  buildTrackedUrl,
};
