/** Каталог целей для внешнего линкбилдинга — 30+ площадок */

const { SITE_URL } = require('./config');

const PLATFORM_LABELS = {
  vc: 'VC.ru',
  dzen: 'Дзен',
  spark: 'СПАРК',
  habr: 'Хабр',
  catalog: 'Каталог',
  partner: 'Партнёр',
  social: 'Соцсеть',
};

function target(path = '/') {
  return path.startsWith('/') ? path : `/${path}`;
}

const EXTERNAL_LINK_CATALOG = [
  // ——— VC.ru ———
  {
    link_key: 'vc-profile',
    platform: 'vc',
    link_type: 'profile',
    title: 'Профиль компании Woner на VC.ru',
    target_path: '/',
    anchor_text: 'Woner.ru — CRM и онлайн-запись для мастеров',
    priority: 10,
    instructions:
      'Создайте профиль компании на vc.ru. В описании — ссылка на woner.ru с UTM. Добавьте логотип, 2–3 скриншота, теги: CRM, бьюти, онлайн-запись.',
    utm_source: 'vc',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },
  {
    link_key: 'vc-article-dikidi',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «Чем заменить DIKIDI в 2026 году»',
    target_path: '/alternativa-dikidi',
    anchor_text: 'альтернатива DIKIDI',
    article_slug: 'chem-zamenit-dikidi',
    priority: 9,
    instructions:
      'Адаптируйте статью из блога (сократите до 4000 знаков). В конце — CTA на woner.ru/alternativa-dikidi. Укажите «Материал подготовлен командой Woner».',
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'alternativa-dikidi',
  },
  {
    link_key: 'vc-article-yclients',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «Чем заменить YCLIENTS»',
    target_path: '/alternativa-yclients',
    anchor_text: 'альтернатива YCLIENTS',
    article_slug: 'chem-zamenit-yclients',
    priority: 9,
    instructions: 'Экспертная колонка с кейсом мастера. Ссылка на лендинг /alternativa-yclients.',
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'alternativa-yclients',
  },
  {
    link_key: 'vc-article-telegram',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «Онлайн-запись через Telegram для салонов»',
    target_path: '/blog/onlajn-zapis-klientov-cherez-telegram',
    anchor_text: 'онлайн-запись через Telegram',
    article_slug: 'onlajn-zapis-klientov-cherez-telegram',
    priority: 8,
    instructions: 'Практический гайд с скриншотами бота. 1–2 ссылки на woner.ru в тексте.',
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'telegram-booking',
  },

  // ——— Дзен ———
  {
    link_key: 'dzen-channel',
    platform: 'dzen',
    link_type: 'profile',
    title: 'Канал Woner в Яндекс Дзен',
    target_path: '/blog',
    anchor_text: 'Woner.ru — блог для мастеров',
    priority: 10,
    instructions:
      'Создайте канал «Woner — CRM для мастеров». Подключите RSS: woner.ru/blog/feed.xml. Публикуйте 2 статьи/нед из блога (автосиндикация).',
    utm_source: 'dzen',
    utm_medium: 'channel',
    utm_campaign: 'blog',
  },
  {
    link_key: 'dzen-article-crm-salon',
    platform: 'dzen',
    link_type: 'article',
    title: 'Дзен: «Лучшие CRM для салона красоты»',
    target_path: '/blog/luchshie-crm-dlya-salona-krasoty',
    anchor_text: 'лучшие CRM для салона красоты',
    article_slug: 'luchshie-crm-dlya-salona-krasoty',
    priority: 8,
    instructions: 'Первая статья вручную + RSS для остальных. Обложка 1200×675.',
    utm_source: 'dzen',
    utm_medium: 'article',
    utm_campaign: 'crm-salon',
  },
  {
    link_key: 'dzen-article-baza-klientov',
    platform: 'dzen',
    link_type: 'article',
    title: 'Дзен: «Как вести базу клиентов салона»',
    target_path: '/blog/kak-vesti-bazu-klientov-salona-krasoty',
    anchor_text: 'база клиентов салона красоты',
    article_slug: 'kak-vesti-bazu-klientov-salona-krasoty',
    priority: 8,
    utm_source: 'dzen',
    utm_medium: 'article',
    utm_campaign: 'client-base',
  },

  // ——— СПАРК ———
  {
    link_key: 'spark-company',
    platform: 'spark',
    link_type: 'profile',
    title: 'Карточка компании в СПАРК (Интерфакс)',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Зарегистрируйте ИП/ООО в СПАРК. Укажите сайт woner.ru в реквизитах. Повышает доверие для B2B-запросов.',
    utm_source: 'spark',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },

  // ——— Хабр ———
  {
    link_key: 'habr-company',
    platform: 'habr',
    link_type: 'profile',
    title: 'Профиль компании на Habr',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Создайте корпоративный аккаунт. Описание: CRM с Telegram/MAX ботами, API для интеграций.',
    utm_source: 'habr',
    utm_medium: 'profile',
    utm_campaign: 'brand',
  },
  {
    link_key: 'habr-article-telegram-bot',
    platform: 'habr',
    link_type: 'article',
    title: 'Хабр: «Как мы сделали онлайн-запись через Telegram-бота»',
    target_path: '/blog/onlajn-zapis-klientov-cherez-telegram',
    anchor_text: 'Telegram-бот для записи клиентов',
    priority: 8,
    instructions:
      'Техническая статья: архитектура бота, webhook, UX. Хабр любит код и диаграммы. Ссылка в конце на woner.ru.',
    utm_source: 'habr',
    utm_medium: 'article',
    utm_campaign: 'telegram-tech',
  },
  {
    link_key: 'habr-article-crm-architecture',
    platform: 'habr',
    link_type: 'article',
    title: 'Хабр: «CRM для мастеров: PostgreSQL + React + боты»',
    target_path: '/register',
    anchor_text: 'попробовать Woner бесплатно',
    priority: 6,
    instructions: 'Кейс разработки продукта. Упор на стек и масштабирование до 1000+ мастеров.',
    utm_source: 'habr',
    utm_medium: 'article',
    utm_campaign: 'dev-story',
  },

  // ——— Каталоги и рейтинги ———
  {
    link_key: 'catalog-startpack',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Startpack.ru — каталог SaaS',
    target_path: '/register',
    anchor_text: 'Woner — CRM для мастеров',
    priority: 9,
    instructions: 'Добавьте продукт в каталог startpack.ru. Категория: CRM / Салоны красоты. Скриншоты + описание.',
    utm_source: 'startpack',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-productradar',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Product Radar — запуск продукта',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 8,
    instructions: 'Подайте заявку на productradar.ru. Подготовьте демо-видео 60 сек.',
    utm_source: 'productradar',
    utm_medium: 'catalog',
    utm_campaign: 'launch',
  },
  {
    link_key: 'catalog-crm-index',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'CRM Index / рейтинг CRM для салонов',
    target_path: '/alternativa-yclients',
    anchor_text: 'Woner — альтернатива YCLIENTS',
    priority: 8,
    instructions: 'Найдите рейтинги «CRM для салонов красоты» и подайте заявку на включение.',
    utm_source: 'crmindex',
    utm_medium: 'catalog',
    utm_campaign: 'rating',
  },
  {
    link_key: 'catalog-yandex-business',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Яндекс Бизнес — карточка организации',
    target_path: '/',
    anchor_text: 'Woner.ru — онлайн-запись',
    priority: 9,
    instructions: 'Создайте карточку в Яндекс Бизнес. Укажите сайт, категорию «Программное обеспечение».',
    utm_source: 'yandex_business',
    utm_medium: 'catalog',
    utm_campaign: 'local',
  },
  {
    link_key: 'catalog-2gis',
    platform: 'catalog',
    link_type: 'catalog',
    title: '2ГИС — карточка компании',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Добавьте компанию в 2ГИС с ссылкой на сайт (для локального SEO).',
    utm_source: '2gis',
    utm_medium: 'catalog',
    utm_campaign: 'local',
  },
  {
    link_key: 'catalog-zoon',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Zoon.ru — IT-сервисы',
    target_path: '/register',
    anchor_text: 'CRM Woner',
    priority: 6,
    utm_source: 'zoon',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-irecommend',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'iRecommend — отзывы о CRM',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 6,
    instructions: 'Создайте страницу продукта, попросите 3–5 мастеров оставить отзывы.',
    utm_source: 'irecommend',
    utm_medium: 'catalog',
    utm_campaign: 'reviews',
  },
  {
    link_key: 'catalog-capterra-ru',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Capterra / GetApp (RU) — CRM',
    target_path: '/',
    anchor_text: 'Woner',
    priority: 7,
    utm_source: 'capterra',
    utm_medium: 'catalog',
    utm_campaign: 'listing',
  },
  {
    link_key: 'catalog-beauty-pro',
    platform: 'catalog',
    link_type: 'catalog',
    title: 'Каталог «Софт для салонов красоты»',
    target_path: '/otrasli',
    anchor_text: 'CRM для бьюти-индустрии',
    priority: 7,
    instructions: 'Профильные подборки софта для салонов — ищите через «CRM салон красоты каталог».',
    utm_source: 'beauty_catalog',
    utm_medium: 'catalog',
    utm_campaign: 'beauty',
  },

  // ——— Партнёрские блоги ———
  {
    link_key: 'partner-beauty-blog',
    platform: 'partner',
    link_type: 'partner',
    title: 'Гостевой пост в бьюти-блоге',
    target_path: '/blog/kak-vesti-bazu-klientov-salona-krasoty',
    anchor_text: 'как вести базу клиентов',
    priority: 8,
    instructions:
      'Найдите блоги мастеров/школ маникюра (10k+ подписчиков). Предложите гостевой пост или обмен ссылками.',
    utm_source: 'partner_blog',
    utm_medium: 'guest_post',
    utm_campaign: 'beauty',
  },
  {
    link_key: 'partner-school-nails',
    platform: 'partner',
    link_type: 'partner',
    title: 'Партнёрство со школой маникюра',
    target_path: '/register',
    anchor_text: 'бесплатная CRM для выпускников',
    priority: 8,
    instructions: 'Договоритесь со школой: выпускникам — бонус на баланс + ссылка в материалах курса.',
    utm_source: 'nail_school',
    utm_medium: 'partner',
    utm_campaign: 'education',
  },
  {
    link_key: 'partner-salon-franchise',
    platform: 'partner',
    link_type: 'partner',
    title: 'Сеть салонов / франшиза',
    target_path: '/resheniya',
    anchor_text: 'CRM для сети салонов',
    priority: 7,
    instructions: 'Предложите white-label или корпоративный тариф. Взамен — ссылка «Рекомендуемый сервис записи».',
    utm_source: 'salon_network',
    utm_medium: 'partner',
    utm_campaign: 'b2b',
  },
  {
    link_key: 'partner-cosmetics-brand',
    platform: 'partner',
    link_type: 'partner',
    title: 'Бренд косметики — коллаборация',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 6,
    instructions: 'Косметические бренды для мастеров часто ведут блоги. Предложите совместный гайд.',
    utm_source: 'cosmetics_brand',
    utm_medium: 'partner',
    utm_campaign: 'collab',
  },
  {
    link_key: 'partner-telegram-channel',
    platform: 'partner',
    link_type: 'mention',
    title: 'Упоминание в Telegram-канале для мастеров',
    target_path: '/register',
    anchor_text: 'онлайн-запись Woner',
    priority: 8,
    instructions: 'Каналы «маникюр бизнес», «салон красоты» — платное или бартерное размещение.',
    utm_source: 'tg_channel',
    utm_medium: 'mention',
    utm_campaign: 'beauty',
  },

  // ——— Соцсети (sameAs + NAP) ———
  {
    link_key: 'social-vk-group',
    platform: 'social',
    link_type: 'profile',
    title: 'Группа ВКонтакте Woner',
    target_path: '/blog',
    anchor_text: 'Woner.ru',
    priority: 7,
    instructions: 'Создайте публичную группу. В описании — ссылка. Репосты статей из блога 2×/нед.',
    utm_source: 'vk',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },
  {
    link_key: 'social-telegram-channel',
    platform: 'social',
    link_type: 'profile',
    title: 'Telegram-канал Woner (новости продукта)',
    target_path: '/',
    anchor_text: 'Woner.ru',
    priority: 7,
    utm_source: 'telegram',
    utm_medium: 'social',
    utm_campaign: 'brand',
  },
  {
    link_key: 'social-youtube',
    platform: 'social',
    link_type: 'profile',
    title: 'YouTube — обзоры и туториалы',
    target_path: '/register',
    anchor_text: 'попробовать Woner',
    priority: 6,
    instructions: 'Короткие видео «Как настроить запись за 5 минут». Ссылка в описании.',
    utm_source: 'youtube',
    utm_medium: 'social',
    utm_campaign: 'video',
  },

  // ——— Дополнительные VC/Дзен ———
  {
    link_key: 'vc-article-manikyur-crm',
    platform: 'vc',
    link_type: 'article',
    title: 'VC.ru: «CRM для мастера маникюра»',
    target_path: '/blog/crm-dlya-mastera-manikyura-gid',
    anchor_text: 'CRM для мастера маникюра',
    article_slug: 'crm-dlya-mastera-manikyura-gid',
    priority: 8,
    utm_source: 'vc',
    utm_medium: 'article',
    utm_campaign: 'manicure-crm',
  },
  {
    link_key: 'dzen-article-manikyur',
    platform: 'dzen',
    link_type: 'article',
    title: 'Дзен: «CRM для маникюра без DIKIDI»',
    target_path: '/alternativa-dikidi',
    anchor_text: 'замена DIKIDI',
    article_slug: 'chem-zamenit-dikidi',
    priority: 7,
    utm_source: 'dzen',
    utm_medium: 'article',
    utm_campaign: 'dikidi',
  },
];

function buildTrackedUrl(targetPath, { utm_source, utm_medium, utm_campaign } = {}) {
  const base = `${SITE_URL}${target(targetPath)}`;
  const params = new URLSearchParams();
  if (utm_source) params.set('utm_source', utm_source);
  if (utm_medium) params.set('utm_medium', utm_medium);
  if (utm_campaign) params.set('utm_campaign', utm_campaign);
  const qs = params.toString();
  return qs ? `${base}?${qs}` : base;
}

module.exports = {
  EXTERNAL_LINK_CATALOG,
  PLATFORM_LABELS,
  buildTrackedUrl,
};
