const db = require('../config/database');
const { generateAllPages } = require('./programmatic');
const { ensurePublicationSchedule } = require('./publicationSchedule');
const { syncArticlePipeline } = require('./articleCron');

async function upsertPage(client, page) {
  // При обновлении сохраняем:
  //  1) AI-обогащённый контент: если content_source = 'ai', не перезаписываем
  //     title/h1/intro/sections/faq/toc — это результат работы articleAiEnricher
  //  2) Ручные правки админки: если extras.manuallyEdited = true, тоже
  //     оставляем контент в покое (только обновляем служебные поля)
  await client.query(
    `INSERT INTO seo_pages (
       slug, page_type, cluster, niche, title, meta_description, h1, intro,
       sections, faq, related_slugs, priority, published, toc, extras
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
     ON CONFLICT (slug) DO UPDATE SET
       page_type = EXCLUDED.page_type,
       cluster = EXCLUDED.cluster,
       niche = EXCLUDED.niche,
       title = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.title ELSE EXCLUDED.title END,
       meta_description = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.meta_description ELSE EXCLUDED.meta_description END,
       h1 = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.h1 ELSE EXCLUDED.h1 END,
       intro = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.intro ELSE EXCLUDED.intro END,
       sections = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.sections ELSE EXCLUDED.sections END,
       faq = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.faq ELSE EXCLUDED.faq END,
       toc = CASE WHEN seo_pages.content_source = 'ai' OR (seo_pages.extras->>'manuallyEdited') = 'true' THEN seo_pages.toc ELSE EXCLUDED.toc END,
       related_slugs = EXCLUDED.related_slugs,
       priority = EXCLUDED.priority,
       published = EXCLUDED.published,
       extras = EXCLUDED.extras,
       updated_at = NOW()`,
    [
      page.slug,
      page.page_type,
      page.cluster,
      page.niche,
      page.title,
      page.meta_description,
      page.h1,
      page.intro,
      JSON.stringify(page.sections),
      JSON.stringify(page.faq),
      page.related_slugs,
      page.priority,
      page.published,
      JSON.stringify(page.toc || []),
      JSON.stringify(page.extras || {}),
    ]
  );
}

async function rebuildInternalLinks(client, pages) {
  await client.query('DELETE FROM seo_internal_links');
  for (const page of pages) {
    for (const toSlug of page.related_slugs || []) {
      const target = pages.find((p) => p.slug === toSlug);
      if (!target) continue;
      await client.query(
        `INSERT INTO seo_internal_links (from_slug, to_slug, anchor, weight)
         VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING`,
        [page.slug, toSlug, target.h1, Math.round((page.priority || 0.5) * 10)]
      );
    }
  }
}

async function seedSeoContent({ force = false } = {}) {
  const pages = generateAllPages();
  const client = await db.connect();

  try {
    await client.query('BEGIN');
    if (force) {
      await client.query('DELETE FROM seo_internal_links');
      await client.query('DELETE FROM seo_pages');
      await client.query('DELETE FROM seo_articles');
    }

    for (const page of pages) {
      await upsertPage(client, page);
    }

    const generatedSlugs = pages.map((p) => p.slug);
    await client.query(
      `UPDATE seo_pages SET published = FALSE, updated_at = NOW()
       WHERE published = TRUE
         AND NOT (slug = ANY($1::text[]))
         AND COALESCE(extras->>'autoGenerated', 'false') <> 'true'`,
      [generatedSlugs]
    );

    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }

  const articleResult = await syncArticlePipeline(db);

  const client2 = await db.connect();
  let publicationSchedule = { rescheduled: 0 };
  try {
    await client2.query('BEGIN');
    if (force || articleResult.added > 100) {
      publicationSchedule = await ensurePublicationSchedule(client2, { force: true });
    }
    await rebuildInternalLinks(client2, pages);
    await client2.query('COMMIT');
  } catch (err) {
    await client2.query('ROLLBACK');
    throw err;
  } finally {
    client2.release();
  }

  return {
    seeded: true,
    pages: pages.length,
    articles: articleResult.total || articleResult.catalog,
    articlesLive: articleResult.live,
    articlesScheduled: articleResult.scheduled,
    articlesAdded: articleResult.added,
    publication: publicationSchedule,
  };
}

module.exports = { seedSeoContent, rebuildInternalLinks };
