const fs = require('fs');
const path = require('path');
const { buildPage } = require('./templates');
const { NICHE_CATALOG } = require('./niches');
const { clusterKeywords, suggestSlugForCluster } = require('./keywordClustering');
const { analyzeContentGaps } = require('./contentGaps');
const { assignSmartRelatedLinks } = require('./contentEngine');

async function ensureIntelligenceTables(db) {
  try {
    await db.query('SELECT 1 FROM seo_keyword_clusters LIMIT 1');
  } catch {
    const sqlPath = path.join(__dirname, '../db/migrations/039_seo_intelligence.sql');
    await db.query(fs.readFileSync(sqlPath, 'utf8'));
  }
}

async function upsertPage(client, page) {
  await client.query(
    `INSERT INTO seo_pages (
       slug, page_type, cluster, niche, title, meta_description, h1, intro,
       sections, faq, related_slugs, priority, published, toc, extras
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
     ON CONFLICT (slug) DO UPDATE SET
       page_type = EXCLUDED.page_type,
       cluster = EXCLUDED.cluster,
       niche = EXCLUDED.niche,
       title = EXCLUDED.title,
       meta_description = EXCLUDED.meta_description,
       h1 = EXCLUDED.h1,
       intro = EXCLUDED.intro,
       sections = EXCLUDED.sections,
       faq = EXCLUDED.faq,
       related_slugs = EXCLUDED.related_slugs,
       priority = EXCLUDED.priority,
       published = EXCLUDED.published,
       toc = EXCLUDED.toc,
       extras = EXCLUDED.extras,
       updated_at = NOW()`,
    [
      page.slug,
      page.page_type,
      page.cluster,
      page.niche,
      page.title,
      page.meta_description,
      page.h1,
      page.intro,
      JSON.stringify(page.sections),
      JSON.stringify(page.faq),
      page.related_slugs,
      page.priority,
      page.published ?? true,
      JSON.stringify(page.toc || []),
      JSON.stringify(page.extras || {}),
    ]
  );
}

async function persistClusters(db, clusters) {
  await db.query('DELETE FROM seo_keyword_clusters');
  for (const c of clusters) {
    await db.query(
      `INSERT INTO seo_keyword_clusters (
         cluster_key, label, intent, niche, keywords, keyword_count,
         total_impressions, total_clicks, avg_position, mapped_slug, status, analyzed_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW())`,
      [
        c.clusterKey,
        c.label,
        c.intent,
        c.niche,
        JSON.stringify(c.keywords.slice(0, 30)),
        c.keywordCount,
        c.totalImpressions,
        c.totalClicks,
        c.avgPosition,
        c.mappedSlug,
        c.status,
      ]
    );
  }
}

async function persistGaps(db, gaps) {
  await db.query('DELETE FROM seo_content_gaps');
  for (const g of gaps) {
    await db.query(
      `INSERT INTO seo_content_gaps (
         slug, path, page_type, impressions, clicks, avg_position,
         issue_type, severity, recommendation, actions, analyzed_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NOW())
       ON CONFLICT (slug, issue_type) DO UPDATE SET
         impressions = EXCLUDED.impressions,
         clicks = EXCLUDED.clicks,
         avg_position = EXCLUDED.avg_position,
         severity = EXCLUDED.severity,
         recommendation = EXCLUDED.recommendation,
         actions = EXCLUDED.actions,
         analyzed_at = NOW()`,
      [
        g.slug,
        g.path,
        g.page_type,
        g.impressions,
        g.clicks,
        g.avg_position,
        g.issue_type,
        g.severity,
        g.recommendation,
        JSON.stringify(g.actions || []),
      ]
    );
  }
}

function buildPageFromCluster(cluster, existingSlugs) {
  const slug = suggestSlugForCluster(cluster);
  if (!slug || existingSlugs.has(slug)) return null;

  const niche = cluster.niche ? NICHE_CATALOG.find((n) => n.id === cluster.niche) : null;
  const intent = cluster.intent || 'general';
  const seoCluster = intent === 'booking' || intent === 'telegram' ? 'booking'
    : intent === 'beauty' ? 'beauty' : 'crm';

  const h1 = cluster.label;
  const topQuery = cluster.keywords?.find((k) => k.origin === 'search')?.query;

  const page = buildPage({
    slug,
    pageType: 'programmatic',
    cluster: seoCluster,
    niche: niche?.id || null,
    nicheLabel: niche?.genitive || null,
    h1Override: h1,
    priority: Math.min(0.72, 0.5 + Math.min(cluster.totalImpressions / 500, 0.2)),
    variant: `auto-${intent}`,
    category: niche?.category || 'services',
  });
  page.extras = {
    autoGenerated: true,
    clusterKey: cluster.clusterKey,
    primaryKeyword: topQuery || h1,
    generatedAt: new Date().toISOString(),
  };
  return page;
}

async function generateLandingPagesFromClusters(db, clusters, { minImpressions = 0 } = {}) {
  const existingRes = await db.query(`SELECT slug FROM seo_pages WHERE published = TRUE`);
  const existingSlugs = new Set(existingRes.rows.map((r) => r.slug));
  const newPages = [];

  for (const cluster of clusters) {
    if (cluster.status !== 'gap' && cluster.status !== 'unmapped') continue;
    if (cluster.mappedSlug) continue;
    if (minImpressions > 0 && cluster.totalImpressions < minImpressions) continue;
    if (cluster.totalImpressions === 0 && cluster.keywords.every((k) => k.origin !== 'search')) {
      continue;
    }

    const page = buildPageFromCluster(cluster, existingSlugs);
    if (page) {
      newPages.push(page);
      existingSlugs.add(page.slug);
    }
  }

  if (!newPages.length) return { generated: 0, slugs: [] };

  const fullRes = await db.query(
    `SELECT slug, niche, cluster, page_type FROM seo_pages WHERE published = TRUE`
  );
  const linked = assignSmartRelatedLinks([...fullRes.rows, ...newPages]);
  const linkMap = new Map(linked.map((p) => [p.slug, p.related_slugs]));

  const client = await db.connect();
  try {
    await client.query('BEGIN');
    for (const page of newPages) {
      page.related_slugs = linkMap.get(page.slug) || page.related_slugs || [];
      await upsertPage(client, page);
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }

  return { generated: newPages.length, slugs: newPages.map((p) => p.slug) };
}

async function runSeoIntelligence(db, { generatePages = true } = {}) {
  await ensureIntelligenceTables(db);

  const [clusters, gapAnalysis] = await Promise.all([
    clusterKeywords(db),
    analyzeContentGaps(db),
  ]);

  await persistClusters(db, clusters);
  await persistGaps(db, gapAnalysis.gaps);

  let pageGen = { generated: 0, slugs: [] };
  if (generatePages) {
    const gapClusters = clusters.filter((c) => c.status === 'gap');
    pageGen = await generateLandingPagesFromClusters(db, gapClusters, { minImpressions: 0 });
    if (!pageGen.generated) {
      pageGen = await generateLandingPagesFromClusters(db, clusters, { minImpressions: 0 });
    }
  }

  const gapClusters = clusters.filter((c) => c.status === 'gap').length;
  const mappedClusters = clusters.filter((c) => c.status === 'mapped').length;

  return {
    analyzedAt: new Date().toISOString(),
    clusters: {
      total: clusters.length,
      mapped: mappedClusters,
      gaps: gapClusters,
      top: clusters.slice(0, 15).map((c) => ({
        label: c.label,
        intent: c.intent,
        impressions: c.totalImpressions,
        keywords: c.keywordCount,
        mappedSlug: c.mappedSlug,
        status: c.status,
      })),
    },
    contentGaps: {
      hasSearchData: gapAnalysis.hasSearchData,
      totalPages: gapAnalysis.totalPages,
      zeroImpressions: gapAnalysis.zeroImpressions,
      recommendations: gapAnalysis.gaps.length,
      top: gapAnalysis.gaps.slice(0, 20),
    },
    pagesGenerated: pageGen,
  };
}

async function loadIntelligenceDashboard(db) {
  await ensureIntelligenceTables(db);

  let clusters = [];
  let gaps = [];
  let stats = { clusterCount: 0, gapCount: 0, zeroImpressions: 0 };

  try {
    const cRes = await db.query(
      `SELECT cluster_key, label, intent, niche, keyword_count, total_impressions, total_clicks,
              avg_position, mapped_slug, status, analyzed_at
       FROM seo_keyword_clusters
       ORDER BY total_impressions DESC, keyword_count DESC
       LIMIT 100`
    );
    clusters = cRes.rows;

    const gRes = await db.query(
      `SELECT slug, path, page_type, impressions, clicks, avg_position,
              issue_type, severity, recommendation, actions, analyzed_at
       FROM seo_content_gaps
       ORDER BY
         CASE severity WHEN 'error' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,
         impressions ASC
       LIMIT 100`
    );
    gaps = gRes.rows.map((r) => ({
      ...r,
      actions: typeof r.actions === 'string' ? JSON.parse(r.actions) : (r.actions || []),
    }));

    const sRes = await db.query(`
      SELECT
        (SELECT COUNT(*)::int FROM seo_keyword_clusters) AS cluster_count,
        (SELECT COUNT(*)::int FROM seo_keyword_clusters WHERE status = 'gap') AS gap_clusters,
        (SELECT COUNT(*)::int FROM seo_content_gaps) AS gap_recommendations,
        (SELECT COUNT(*)::int FROM seo_content_gaps WHERE issue_type = 'zero_impressions') AS zero_impressions
    `);
    stats = sRes.rows[0] || stats;
  } catch {
    /* empty */
  }

  return { clusters, gaps, stats, analyzedAt: clusters[0]?.analyzed_at || gaps[0]?.analyzed_at || null };
}

module.exports = {
  runSeoIntelligence,
  loadIntelligenceDashboard,
  generateLandingPagesFromClusters,
  ensureIntelligenceTables,
};
